### ISSUE TITLE
FeatureRequest

### ISSUE THREAD

**Issue by brianvessey** [jasonyates/netbox-documents#12]
This is Awesome!

It's allowed me to attach service contract docs to my device inventory items. :)

Would it be possible to have this function available for the DeviceType as well?

That would allow model-specific documents (user manuals, EoL docs etc) to be linked to the model instead of having to link to each instance of the device-type.

Thanks for the great add-on for Netbox, let me know if you want a test-case.

**Comment by LHBL2003** [comment]
Provided with the pull request, if this is released: https://github.com/jasonyates/netbox-documents/pull/16

@jasonyates I ask for your release. 
@jasonyates Importantly, the bug that files are not deleted from the server still exists.

**Comment by jasonyates** [comment]
This is added by PR #16 from @LHBL2003 

Thanks!

**Comment by brianvessey** [comment]
Just got back from holidays.  Looks great, Thanks!
