### ISSUE TITLE
Feature Request: Link to online document option

### ISSUE THREAD

**Issue by dutchman80** [jasonyates/netbox-documents#13]
It would be great if there was a radio button to enable you to paste in a link to a shared document (i.e. Google Docs or online user manual) as opposed to uploading an actual file.

**Comment by jasonyates** [comment]
@dutchman80 Is this what you had in mind? You can choose between uploading a file or linking to a URL.

<img width="766" alt="Screenshot 2023-01-05 at 19 55 38" src="https://user-images.githubusercontent.com/242483/210868688-1678f054-fb6a-4a17-9872-95303aadaa01.png">
<img width="852" alt="Screenshot 2023-01-05 at 19 55 32" src="https://user-images.githubusercontent.com/242483/210868693-2674d59e-c603-4e35-82e3-a3140d03177d.png">
<img width="695" alt="Screenshot 2023-01-05 at 19 55 22" src="https://user-images.githubusercontent.com/242483/210868698-4a1089da-b82b-471c-854e-b805140a80db.png">

**Comment by dutchman80** [comment]
Yes, exactly!

**Comment by deku-m** [comment]
Yes very nice addition to have.

**Comment by jasonyates** [comment]
I published v0.5.0 that has support for URL filtering.
