### ISSUE TITLE
Feature Request add Document to device-types

### ISSUE THREAD

**Issue by AS-MBN** [jasonyates/netbox-documents#15]
each Device-Type has specific HowTos, Installation Sheets, etc.
Please add the documentation feature also to 
DEVICES -> Device Types

Thank you in advance.
Martin

**Comment by LHBL2003** [comment]
Provided with the pull request, if this is released: https://github.com/jasonyates/netbox-documents/pull/16

@jasonyates I ask for your release.

**Comment by jasonyates** [comment]
This is added by PR #16 from @LHBL2003 

Thanks!
