### ISSUE TITLE
Error with add document to custom field 

### ISSUE THREAD

**Issue by EAleg** [jasonyates/netbox-documents#20]
Hi, before Error will display, i'll create **Special Field** (for example License), in **Special Field** in **Type** i choose "Object", "Object Type - Document Storage> Device Document", **Model(s)** (DCIM>Device). 
![image](https://user-images.githubusercontent.com/82929335/213918878-444dc73d-bc98-42dc-a061-232f2e84b1f6.png)

Then i'll going on another Device, and when i Add/Edit **Device** to add some file to my License field i see error.
![image](https://user-images.githubusercontent.com/82929335/213919004-c110cc8c-7c41-4e6f-b408-a55ec1ff2023.png)

![image](https://user-images.githubusercontent.com/82929335/213919047-35df28f8-8ab3-47fe-9208-65a55bd136fb.png)

**Comment by jasonyates** [comment]
Thanks for reporting.

I just published version 0.4.6 that should fix this for you. Please run `pip install netbox-documents --upgrade` to pull the updated release.
