### ISSUE TITLE
Linkify the related objects

### ISSUE THREAD

**Issue by abhi1693** [jasonyates/netbox-documents#3]
I have uploaded a few documents and when viewing them from the plugin side, I would like to directly click on the related objects to open those pages up

Here, I would prefer if I could click on the Site `DUBLIN`
![image](https://user-images.githubusercontent.com/5083532/161633838-9f38ac8a-af2f-4d5b-bd5b-dd76314b493f.png)

Maybe the `filename` should also be made clickable to view it?

**Comment by jasonyates** [comment]
I'll release v0.3.1 likely tomorrow with these changes. Nice suggestion, thanks.
