### ISSUE TITLE
Error post request device-document

### ISSUE THREAD

**Issue by strelez13** [jasonyates/netbox-documents#33]
**Netbox version 3.5.1**
Plugin version 0.6.0
I'm posting device-document 'Content-Type: multipart/form-data' to swagger-ui and getting error {
   "device": [
     "This field is required."
   ]
}

**Comment by silvije2** [comment]
I am trying to upload document

curl --header 'Authorization: Token xxx' -F document_type="other" -F name="name" -F circuit=590 -F document=@path "https://mynetbox/api/plugins/documents/circuit-documents/"

and I got error {"circuit":["This field is required."]}

any help?

**Comment by jasonyates** [comment]
This will be fixed in 0.6.2
