### ISSUE TITLE
Feature Request: Add support to attach documents to locations within a site

### ISSUE THREAD

**Issue by JLawrence14** [jasonyates/netbox-documents#36]
Documents can be added to sites, but we also have multiple locations within a site, that each have separate documentation. Could the Site Documentation model be enhanced by allowing location assignment based on the site selected.

Site Documentation -> Site -> Location

Thanks,

Jamie

**Comment by NetworkSeb** [comment]
Yes please!

**Comment by marcosmas28** [comment]
Hi, has anyone tried to extend this plugin to Location objects?
Any guideline or clue on how to do this?
Thanks in advance!

**Comment by jasonyates** [comment]
Hi, this is included in 0.6.2 release thanks to PR #44
