### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by Geunzai** [jasonyates/netbox-documents#43]
Hi, first of all, I'm new to Github, Netbox and all plugins (I should say, I'm new to IT field, still learning), so apologies in advance, if I say something wrong, not allowed, or illogical.  

My company has some combination locks for doors, cabinets, and boxes in IT server room.  I was looking for a tool that's saving these combinations and passwords in Netbox and found out another plugin called Netbox-Secret.  Netbox-secret works just fine when it comes to store passwords for devices, VMs, and etc.  However, I need to be able to document passcodes for the sites under Netbox-documents, and Netbox-Secret doesn't seem to work with Netbox-documents.  I have approached to Netbox-Secret developer and advised me to ask Netbox-document developer to include the plugin related tags in your template.

I'm just wondering if this is doable. 

I really appreciate with you developing, maintaining, and updating this plugin for users including myself to help organizing IT related documents.

**Comment by jasonyates** [comment]
Hi, thanks for the feature request. This will be supported in the 0.6.2 release.
