### ISSUE TITLE
Linking VRFS

### ISSUE THREAD

**Issue by LewisDi** [jasonyates/netbox-documents#52]
Im looking for the abilities to link multiple VRFS together. 

We will often use Multiple VRFs on the same hardware which will route to each other via a Firewall. However i cant ensure uniqueness across multiple VRFS without manually checking before hand.

**Comment by felbinger** [comment]
Is this issue related to netbox or to netbox-documents? I don't think this plugin is modifying VRFs in any way :thinking:

**Comment by jasonyates** [comment]
Unfortunately this plugin is not suited for what you are requesting. Perhaps a FR at Netbox itself may prove more fruitful.
