### ISSUE TITLE
Prepare plugin for NetBox v4.0.x

### ISSUE THREAD

**Issue by litebito** [jasonyates/netbox-documents#59]
Can the plugin be prepared (or a version be made) which supports NetBox v4.0.0?

**Comment by deku-m** [comment]
Having troubles now with 4.0 indeed when upgrading.

**Comment by david-sieg** [comment]
> Having troubles now with 4.0 indeed when upgrading. Can we bring this under the netbox-community to maintain?

That would be nice! +1

**Comment by cameronw1996** [comment]
Would be great to have this done! +1

**Comment by Azmodeszer** [comment]
Would be nice indeed! +1

**Comment by LordZorgon** [comment]
Is any help needed for a new version of the plugin?

**Comment by HomerJaySimpson13** [comment]
do we know what the status is?  i'm kinda new to this.  i made the changes manual and now my netbox quit working, so i wiped out my changes.  I'd love to know when we might be able to use this amazing plugin.
