### ISSUE TITLE
Issues with migration after install

### ISSUE THREAD

**Issue by nsauter** [jasonyates/netbox-documents#61]
Hello!

I installed netbox-documents v0.6.4 in my Netbox 3.6 Installation (its that old because i need some plugins which havent been officially supported in newer versions like this one) and im getting this error:

django.db.migrations.exceptions.NodeNotFoundError: Migration netbox_documents.0006_vmdocument dependencies reference nonexistent parent node ('extras', '0106_bookmark_user_cascade_deletion')

All i do is to execute python3 manage.py migrate after i installed everything and added it to the configuration.py. Could somebody please tell me what i need to do?

Thanks!

**Comment by a084ed22** [comment]
You need a more up to date version of netbox, or an older version of the plugin. The error indicates a dependency on a migration that's part of core netbox but that is not present in your instance.

**Comment by nsauter** [comment]
As mentioned in the other issue i wasnt aware of that since i installed the plugin version for 3.6 and because its not mentioned with v4 i didn know it should work with v4. Im trying a newer version now...

**Comment by 1024834** [comment]
👀

**Comment by jasonyates** [comment]
Version 0.7.0 of the plugin is released to be compatible with Netbox 4.0+
