### ISSUE TITLE
Where are document files stored?

### ISSUE THREAD

**Issue by joaolucasmacedo** [jasonyates/netbox-documents#7]
I'm just wondering where are the document files stored, so when I run a Netbox or plugin upgrade I can copy it to the new folder and make a proper migration. 

Also, is there a proper way to backup or export documents?

**Comment by jasonyates** [comment]
Document storage follows the Netbox `STORAGE_BACKEND` configuration.

If you are using the default configuration, it creates a new folder `netbox-documents/` within the existing `netbox/media/ ` path. So following the Netbox upgrade documentation will ensure the documents are migrated as part of this command:

`sudo cp -pr /opt/netbox-X.Y.Z/netbox/media/ /opt/netbox/netbox/`
