### ISSUE TITLE
The file is not deleted from server

### ISSUE THREAD

**Issue by 3bruno** [jasonyates/netbox-documents#9]
Hi. When I delete a document from Netbox GUI, the file is not deleted from server.

Can you check?

**Comment by LHBL2003** [comment]
@jasonyates: I can confirm the problem. We need your help here, I definitely have too little experience with Python and Django to find the problem.

**Comment by jasonyates** [comment]
This is fixed in PR #17 

Thanks for reporting!

**Comment by via78** [comment]
thank you!
after i installed the latest version and restart  Netbox delete  Worked as expected again.
